<?php
/**
 * @file
 * Drupal DDP Users module
 */

/**
 * Implements hook_entity_insert().
 */
function drupal_ddp_users_entity_insert($entity, $type) {
  switch ($type) {
    case 'user':
    	$entity->ddp_type = 'user';
      drupal_ddp_send_content($entity);
      break;
  }
}

/**
 * Implements hook_entity_update().
 */
function drupal_ddp_users_entity_update($entity, $type) {
  switch ($type) {
    case 'user':
      $entity->ddp_type = 'user';
      drupal_ddp_send_content($entity);
      break;
  }
}

/**
 * Implements hook_entity_delete().
 */
function drupal_ddp_users_entity_delete($entity, $type) {
  // Set 'delete_content' flag to be used in Meteor.
  $entity->delete_content = TRUE;

  switch ($type) {
    case 'user':
      $entity->ddp_type = 'user';
      drupal_ddp_send_content($entity);
      break;
  }
}